# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: gqlc
metadata:
  maintainers:
    - Frank Mayer
  license: Zlib
  homepage: https://github.com/tsukinoko-kun/gqlc
  description: GraphQL compiler
  full_description:
    from_file:
      path: ./README.md

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.buildVersion={{.Version}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

npms:
  - name: "@tsukinoko-kun/gqlc"
    id: gqlc
    access: public
    url_template: "https://github.com/tsukinoko-kun/gqlc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository: https://github.com/tsukinoko-kun/gqlc
    bugs: https://github.com/tsukinoko-kun/gqlc/issues

brews:
  - name: gqlc
    url_template: "https://github.com/tsukinoko-kun/gqlc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_headers:
      - "Accept: application/octet-stream"
      - 'Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}'
    repository:
      owner: tsukinoko-kun
      name: homebrew-tap
      branch: main

scoops:
  - name: gqlc
    url_template: "https://github.com/tsukinoko-kun/gqlc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: tsukinoko-kun
      name: scoop-bucket
      branch: main
